name: Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace --no-daemon
